# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c856b13add41f9c201130d5de4506c530898dbc68660f654eb7ca688c7e40bc4535fa5c1906cbefcc6e18382e053b2535f97a301f15493c21fd552d7e09c02c

test:
  secret_key_base: 194be76e93d5407e475324fcb9f8bcd507252daf28204d61873c3337a13a8e8b1a0179eeda3e20c515244dd76968cb8de720c46dfe04ec0cd97e403f10bd2a55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
